#include "SpinParser.h"

using namespace std::string_literals;
using namespace std::string_view_literals;

const std::array targetKeywordVec = {
	std::vector<std::string>{"KR", "kr", "kalvinritter", "kal", "kalvin", "sparrow", "thesparrow", "ritter"},
	std::vector<std::string>{"JK", "jk", "jasper", "jasperknight", "knight"},
	std::vector<std::string>{"VN", "vn", "viktornovikov", "vic", "victor", "vik", "viktor", "novikov"},
	std::vector<std::string>{"DM", "dm", "daliamargolis", "dalia", "dahlia", "margolis"},
	std::vector<std::string>{"HSB", "hb", "hsb", "harrysmokeybagnato", "harrybagnato", "smokey", "bagnato"},
	std::vector<std::string>{"MSG", "msg", "mg", "marvslickgonif", "marvgonif", "slick", "marv", "gonif"},
	std::vector<std::string>{"SC", "sc", "silviocaruso", "silv", "silvio", "caruso"},
	std::vector<std::string>{"FDS", "fds", "francescadesantis", "fran", "frann", "franny", "francesca", "desantis", "santis", "frannydesanny", "sanny", "desanny"},
	std::vector<std::string>{"DB", "db", "dinobosco", "dino", "bosco", "ironman"},
	std::vector<std::string>{"MA", "ma", "marcoabiatti", "marco", "abiatti"},
	std::vector<std::string>{"CB", "cb", "craigblack", "craig", "black"},
	std::vector<std::string>{"BA", "ba", "brotherakram", "brother", "akram"},
	std::vector<std::string>{"CHS", "chs", "claushugostrandberg", "hugo", "claus", "strandberg", "stranberg", "clausstrandberg", "clausstranberg", "claushugostranberg"},
	std::vector<std::string>{"RZ", "rz", "grz", "rezazaydan", "reza", "rez", "zaydan", "general", "generalrezazaydan", "generalzaydan"},
	std::vector<std::string>{"KTK", "ktk", "kongtuokwang", "kk", "kong", "tuo", "kwang", "tuokwang", "kongkwang", "kang", "kwong"},
	std::vector<std::string>{"MM", "mm", "matthieumendola", "mat", "matt", "matthieu", "mendola"},
	std::vector<std::string>{"JC", "jc", "jordancross", "jordan", "cross", "jord"},
	std::vector<std::string>{"KM", "km", "kenmorgan", "ken", "morgan", "thebrick", "brick", "kenthebrickmorgan"},
	std::vector<std::string>{"ON", "on", "oybeknabazov", "oybek", "nabazov", "oy", "nab", "oynab"},
	std::vector<std::string>{"SY", "sy", "sisteryulduz", "sister", "yulduz", "sis"},
	std::vector<std::string>{"SR", "sr", "seanrose", "sean", "rose"},
	std::vector<std::string>{"PG", "pg", "penelopegraves", "penelope", "graves", "pen", "penny", "pennylope", "penylope", "gravez"},
	std::vector<std::string>{"EB", "eb", "ezraberg", "ezra", "berg", "ez"},
	std::vector<std::string>{"MP", "mp", "mayaparvati", "maya", "parvati"},
	std::vector<std::string>{"ES", "es", "erichsoders", "erich", "ericsoders", "eric", "soders", "sodas"},
	std::vector<std::string>{"YY", "yy", "yukiyamazaki", "yuki", "yamazaki"},
	std::vector<std::string>{"OC", "oc", "owencage", "owen", "cage"},
	std::vector<std::string>{"KL", "kl", "klausliebleid", "klaus", "liebleid"},
	std::vector<std::string>{"DF", "df", "dmitrifedorov", "dmitri", "fedorov", "dimitri"},
	std::vector<std::string>{"AR", "ar", "almareynard", "alma", "reynard"},
	std::vector<std::string>{"SK", "sk", "sierraknox", "sierra", "siera"},
	std::vector<std::string>{"RK", "rk", "robertknox", "robert", "rob", "bob", "robknox", "bobknox", "bobby", "bobbyknox", "bobertknox", "bobert"},
	std::vector<std::string>{"AJ", "aj", "ajitajkrish", "aak", "ak", "ajitkrish", "ajit", "krish"},
	std::vector<std::string>{"RD", "rd", "ricodelgado", "rico", "delgado", "ric"},
	std::vector<std::string>{"JF", "jf", "jorgefranco", "jorge", "franco", "jorg", "franc", "jorj"},
	std::vector<std::string>{"AM", "am", "andreamartinez", "andrea", "martinez"},
	std::vector<std::string>{"BR", "br", "blairreddington", "blair", "reddington"},
	std::vector<std::string>{"WK", "wk", "wazirkale", "wazir", "kale", "themaelstrom", "maelstrom", "malestrom", "waz"},
	std::vector<std::string>{"VS", "vs", "vanyashah", "vanya", "shah"},
	std::vector<std::string>{"DR", "dr", "dawoodrangan", "dawood", "rangan"},
	std::vector<std::string>{"BC", "bc", "basilcarnaby", "basil", "carnaby", "bas"},
	std::vector<std::string>{"J", "j", "janus", "jan"},
	std::vector<std::string>{"NC", "nc", "nolancassidy", "nolan", "cassidy"},
	std::vector<std::string>{"GV", "gv", "galenvholes", "galen", "vholes", "gale"},
	std::vector<std::string>{"ZW", "zw", "zoewashington", "zoe"},
	std::vector<std::string>{"SW", "sw", "sophiawashington", "sophia", "soph"},
	std::vector<std::string>{"AS", "as", "athenasavalas", "athena", "savalas", "ath", "athen"},
	std::vector<std::string>{"TW", "tw", "tysonwilliams", "tyson", "williams", "ath", "tys"},
	std::vector<std::string>{"SB", "sb", "stevenbradley", "steven", "steve", "bradley"},
	std::vector<std::string>{"LV", "lv", "ljudmilavetrova", "ljudmila", "vetrova", "ljud"},
	std::vector<std::string>{"CI", "ci", "carlingram", "carl", "ingram"},
	std::vector<std::string>{"MS", "ms", "marcusstuyvesant", "marcus", "stuyvesant", "marc"},
	std::vector<std::string>{"AC", "ac", "alexacarlisle", "alexa", "carlisle"},
	std::vector<std::string>{"H", "h", "hush", "hushthebastard", "thebastard", "bastard"},
	std::vector<std::string>{"IR", "ir", "imogenroyce", "imogen", "royce"},
	std::vector<std::string>{"DY", "dy", "donarchibaldyates", "don", "archibald", "yates", "day", "don", "yates", "donyates"},
	std::vector<std::string>{"TV", "tv", "tamaravidal", "tamara", "vidal", "tam", "tammy"},
	std::vector<std::string>{"AE", "ae", "arthuredwards", "arthur", "edwards"},
	std::vector<std::string>{"NCR", "ncr", "noelcrest", "noel", "crest"},
	std::vector<std::string>{"SV", "sv", "sinhiakkaventham", "sav", "sinhi", "akka", "ventham", "akkaventham", "sinhiventham", "akk"},
	std::vector<std::string>{"1", "1", "1st"},
	std::vector<std::string>{"2", "2", "2nd"},
	std::vector<std::string>{"3", "3", "3rd"},
	std::vector<std::string>{"4", "4", "4th"},
	std::vector<std::string>{"5", "5", "5th"},
};

std::unordered_map<std::string, std::string> targetKeywords;
const std::unordered_map<std::string, std::string> keywordKeywords = {
	{"bg", "bodyguard"},
	{"bgd", "bodyguard"},
	{"bdgd", "bodyguard"},
	{"bdygd", "bodyguard"},
	{"bdygrd", "bodyguard"},
	{"bgrd", "bodyguard"},
	{"bdgrd", "bodyguard"},
	{"cocoa", "coca"},
	{"drvr", "driver"},
	{"mech", "mechanic"},
	{"shiek", "sheikh"},
	{"sheik", "sheikh"},
	{"shiekh", "sheikh"},
	{"shake", "sheikh"},
	{"vamp", "vampire"},
	{"dracula", "vampire"},
	{"hippy", "hippie"},
	{"bicyclist", "cyclist"},
	{"garden", "gardener"},
	{"gardner", "gardener"},
	{"guardener", "gardener"},
	{"housekpr", "housekeeper"},
	{"housekper", "housekeeper"},
	{"housekeper", "housekeeper"},
	{"housekeep", "housekeeper"},
	{"groundkeeper", "groundskeeper"},
	{"miltia", "militia"},
	{"kron", "kronstadt"},
	{"kronst", "kronstadt"},
	{"kronstad", "kronstadt"},
	{"kronstat", "kronstadt"},
	{"krondstat", "kronstadt"},
	{"krondstadt", "kronstadt"},
	{"bollywd", "bollywood"},
	{"bllywd", "bollywood"},
	{"blywd", "bollywood"},
	{"bollywod", "bollywood"},
	{"bolly", "bollywood"},
	{"servent", "servant"},
	{"armour", "armor"},
	{"famos", "famous"},
	{"maintenence", "maintenance"},
	{"maintainance", "maintenance"},
	{"maintainence", "maintenance"},
	{"fac", "facility"},
	{"facil", "facility"},
	{"analist", "analyst"},
	{"guacho", "gaucho"},
	{"somelier", "sommelier"},
	{"sacraficial", "sacrificial"},
	{"millitary", "military"},
	{"prison", "prisoner"},
};
const std::vector<DisguiseKeywords> disguiseKeywords = {
	DisguiseKeywords{{}, {{"suit", "Suit"}}},
	DisguiseKeywords{{eMission::ICAFACILITY_GUIDED, eMission::ICAFACILITY_FREEFORM}, {
		{"bodyguard", "Bodyguard"},
		{"guard", "Bodyguard"},
		{"mechanic", "Mechanic"},
		{"terrynorfolk", "Terry Norfolk"},
		{"terry", "Terry Norfolk"},
		{"norfolk", "Terry Norfolk"},
		{"crew", "Yacht Crew"},
		{"yachtcrew", "Yacht Crew"},
		{"yachtsecurity", "Yacht Security"},
		{"security", "Yacht Security"},
	}},
	DisguiseKeywords{{eMission::ICAFACILITY_FINALTEST}, {
		{"security", "Airfield Security"},
		{"guard", "Airfield Security"},
		{"mechanic", "Airplane Mechanic"},
		{"kgbofficer", "KGB Officer"},
		{"kgb", "KGB Officer"},
		{"officer", "KGB Officer"},
		{"soldier", "Soviet Soldier"},
		{"sovietsoldier", "Soviet Soldier"},
		{"soviet", "Soviet Soldier"},
	}},
	DisguiseKeywords{{eMission::PARIS_SHOWSTOPPER, eMission::PARIS_HOLIDAYHOARDERS}, {
		{"auction", "Auction Staff"},
		{"auctioneer", "Auction Staff"},
		{"auctionstaff", "Auction Staff"},
		{"chef", "Chef"},
		{"cook", "Chef"},
		{"bodyguard", "CICADA Bodyguard"},
		{"cicada", "CICADA Bodyguard"},
		{"cicadabodyguard", "CICADA Bodyguard"},
		{"helmut", "Helmut Kruger"},
		{"kruger", "Helmut Kruger"},
		{"helmutkruger", "Helmut Kruger"},
		{"palace", "Palace Staff"},
		{"staff", "Palace Staff"},
		{"waiter", "Palace Staff"},
		{"palacestaff", "Palace Staff"},
		{"security", "Security Guard"},
		{"guard", "Security Guard"},
		{"securityguard", "Security Guard"},
		{"sec", "Security Guard"},
		{"secguard", "Security Guard"},
		{"sheikh", "Sheikh Salman Al-Ghazali"},
		{"salman", "Sheikh Salman Al-Ghazali"},
		{"alghazali", "Sheikh Salman Al-Ghazali"},
		{"ghazali", "Sheikh Salman Al-Ghazali"},
		{"sheikhsalman", "Sheikh Salman Al-Ghazali"},
		{"sheikhsalmanal", "Sheikh Salman Al-Ghazali"},
		{"sheikhsalmanalghazali", "Sheikh Salman Al-Ghazali"},
		{"salmanalghazali", "Sheikh Salman Al-Ghazali"},
		{"stylist", "Stylist"},
		{"tech", "Tech Crew"},
		{"techcrew", "Tech Crew"},
		{"crew", "Tech Crew"},
		{"roadie", "Tech Crew"},
		{"stagecrew", "Tech Crew"},
		{"vampiremagician", "Vampire Magician"},
		{"vampire", "Vampire Magician"},
		{"magician", "Vampire Magician"},
	}},
	DisguiseKeywords{{eMission::PARIS_HOLIDAYHOARDERS}, {
		{"santaclaus", "Santa"},
		{"santa", "Santa"},
		{"saintnick", "Santa"},
		{"hohoho", "Santa"},
	}},
	DisguiseKeywords{{eMission::SAPIENZA_WORLDOFTOMORROW}, {
		{"biolab", "Biolab Security"},
		{"bioguard", "Biolab Security"},
		{"biosecurity", "Biolab Security"},
		{"biolabguard", "Biolab Security"},
		{"biolabsecurity", "Biolab Security"},
		{"labsecurity", "Biolab Security"},
		{"labguard", "Biolab Security"},
		{"caveguard", "Biolab Security"},
		{"cavesecurity", "Biolab Security"},
		{"bodyguard", "Bodyguard"},
		{"cicada", "Bodyguard"},
		{"bohemian", "Bohemian"},
		{"hippie", "Bohemian"},
		{"torres", "Bohemian"},
		{"piombo", "Bohemian"},
		{"torrespiombo", "Bohemian"},
		{"butler", "Butler"},
		{"chef", "Chef"},
		{"churchstaff", "Church Staff"},
		{"church", "Church Staff"},
		{"cyclist", "Cyclist"},
		{"delivery", "Delivery Man"},
		{"deliveryman", "Delivery Man"},
		{"deliveryguy", "Delivery Man"},
		{"lafayette", "Dr. Oscar Lafayette"},
		{"drlafayette", "Dr. Oscar Lafayette"},
		{"oscar", "Dr. Oscar Lafayette"},
		{"droscarlafayette", "Dr. Oscar Lafayette"},
		{"oscarlafayette", "Dr. Oscar Lafayette"},
		{"laf", "Dr. Oscar Lafayette"},
		{"laff", "Dr. Oscar Lafayette"},
		{"dr", "Dr. Oscar Lafayette"},
		{"gardener", "Gardener"},
		{"gplumber", "Green Plumber"},
		{"grnplumber", "Green Plumber"},
		{"luigi", "Green Plumber"},
		{"luigimario", "Green Plumber"},
		{"greenplumber", "Green Plumber"},
		{"hazmatsuit", "Hazmat Suit"},
		{"hazardsuit", "Hazmat Suit"},
		{"biosuit", "Hazmat Suit"},
		{"hazmat", "Hazmat Suit"},
		{"housekeeper", "Housekeeper"},
		{"kitchenstaff", "Kitchen Assistant"},
		{"kitchenassistant", "Kitchen Assistant"},
		{"kitchenass", "Kitchen Assistant"},
		{"kitchensass", "Kitchen Assistant"},
		{"kitchensassistant", "Kitchen Assistant"},
		{"rocco", "Kitchen Assistant"},
		{"labtechnician", "Lab Technician"},
		{"labtech", "Lab Technician"},
		{"lab", "Lab Technician"},
		{"technician", "Lab Technician"},
		{"scientist", "Lab Technician"},
		{"mansionsecurity", "Mansion Security"},
		{"housesecurity", "Security"},
		{"villasecurity", "Security"},
		{"houseguard", "Security"},
		{"mansionguard", "Security"},
		{"villaguard", "Security"},
		{"guard", "Security"},
		{"security", "Security"},
		{"mansionstaff", "Mansion Staff"},
		{"mansion", "Mansion Staff"},
		{"staff", "Mansion Staff"},
		{"plague", "Plague Doctor"},
		{"plaguedoctor", "Plague Doctor"},
		{"doctor", "Plague Doctor"},
		{"priest", "Priest"},
		{"padre", "Priest"},
		{"fadre", "Priest"},
		{"privatedetective", "Private Detective"},
		{"detective", "Private Detective"},
		{"pi", "Private Detective"},
		{"pd", "Private Detective"},
		{"privateinvestigator", "Private Detective"},
		{"investigator", "Private Detective"},
		{"robertovargas", "Roberto Vargas"},
		{"roberto", "Roberto Vargas"},
		{"vargas", "Roberto Vargas"},
		{"coach", "Roberto Vargas"},
		{"instructor", "Roberto Vargas"},
		{"golfcoach", "Roberto Vargas"},
		{"golfinstructor", "Roberto Vargas"},
		{"golf", "Roberto Vargas"},
		{"robert", "Roberto Vargas"},
		{"redplumber", "Red Plumber"},
		{"rplumber", "Red Plumber"},
		{"mariomario", "Red Plumber"},
		{"mario", "Red Plumber"},
		{"rdplumber", "Red Plumber"},
		{"storeclerk", "Store Clerk"},
		{"store", "Store Clerk"},
		{"clerk", "Store Clerk"},
		{"shop", "Store Clerk"},
		{"shopkeeper", "Store Clerk"},
		{"storekeeper", "Store Clerk"},
		{"streetperformer", "Street Performer"},
		{"jingles", "Street Performer"},
		{"clown", "Street Performer"},
		{"performer", "Street Performer"},
		{"jester", "Street Performer"},
		{"mime", "Street Performer"},
		{"juggler", "Street Performer"},
		{"waiter", "Waiter"},
	}},
	DisguiseKeywords{{eMission::SAPIENZA_THEAUTHOR}, {
		{"bodyguard", "Bodyguard"},
		{"guard", "Bodyguard"},
		{"cicada", "Bodyguard"},
		{"bohemian", "Bohemian"},
		{"hippie", "Bohemian"},
		{"torres", "Bohemian"},
		{"piombo", "Bohemian"},
		{"torrespiombo", "Bohemian"},
		{"brotherakram", "Brother Akram"},
		{"brother", "Brother Akram"},
		{"akram", "Brother Akram"},
		{"chef", "Chef"},
		{"churchstaff", "Church Staff"},
		{"church", "Church Staff"},
		{"craigblack", "Craig Black"},
		{"craig", "Craig Black"},
		{"black", "Craig Black"},
		{"gardener", "Gardener"},
		{"gplumber", "Green Plumber"},
		{"grnplumber", "Green Plumber"},
		{"luigi", "Green Plumber"},
		{"luigimario", "Green Plumber"},
		{"greenplumber", "Green Plumber"},
		{"housekeeper", "Housekeeper"},
		{"kitchenstaff", "Kitchen Assistant"},
		{"kitchenassistant", "Kitchen Assistant"},
		{"kitchenass", "Kitchen Assistant"},
		{"kitchensass", "Kitchen Assistant"},
		{"kitchensassistant", "Kitchen Assistant"},
		{"rocco", "Kitchen Assistant"},
		{"redplumber", "Red Plumber"},
		{"rplumber", "Red Plumber"},
		{"mariomario", "Red Plumber"},
		{"mario", "Red Plumber"},
		{"rdplumber", "Red Plumber"},
		{"salvatorebravuomo", "Salvatore Bravuomo"},
		{"sal", "Salvatore Bravuomo"},
		{"salvatore", "Salvatore Bravuomo"},
		{"bravuomo", "Salvatore Bravuomo"},
		{"bravomo", "Salvatore Bravuomo"},
		{"bravumo", "Salvatore Bravuomo"},
		{"sfxcrew", "SFX Crew"},
		{"fxcrew", "SFX Crew"},
		{"sfx", "SFX Crew"},
		{"crew", "SFX Crew"},
		{"superfan", "Super Fan"},
		{"fan", "Super Fan"},
		{"waiter", "Waiter"},
	} },
	DisguiseKeywords{{eMission::SAPIENZA_LANDSLIDE}, {
		{"bodyguard", "Bodyguard"},
		{"guard", "Bodyguard"},
		{"cicada", "Bodyguard"},
		{"bohemian", "Bohemian"},
		{"hippie", "Bohemian"},
		{"torres", "Bohemian"},
		{"piombo", "Bohemian"},
		{"torrespiombo", "Bohemian"},
		{"churchstaff", "Church Staff"},
		{"church", "Church Staff"},
		{"gardener", "Gardener"},
		{"gplumber", "Green Plumber"},
		{"grnplumber", "Green Plumber"},
		{"luigi", "Green Plumber"},
		{"luigimario", "Green Plumber"},
		{"greenplumber", "Green Plumber"},
		{"kitchenstaff", "Kitchen Assistant"},
		{"kitchenassistant", "Kitchen Assistant"},
		{"kitchenass", "Kitchen Assistant"},
		{"kitchensass", "Kitchen Assistant"},
		{"kitchensassistant", "Kitchen Assistant"},
		{"rocco", "Kitchen Assistant"},
		{"photographer", "Photographer"},
		{"photo", "Photographer"},
		{"priest", "Priest"},
		{"padre", "Priest"},
		{"fadre", "Priest"},
		{"rplumber", "Red Plumber"},
		{"mariomario", "Red Plumber"},
		{"mario", "Red Plumber"},
		{"rdplumber", "Red Plumber"},
		{"salvatorebravuomo", "Salvatore Bravuomo"},
		{"sal", "Salvatore Bravuomo"},
		{"salvatore", "Salvatore Bravuomo"},
		{"bravuomo", "Salvatore Bravuomo"},
		{"bravomo", "Salvatore Bravuomo"},
		{"bravumo", "Salvatore Bravuomo"},
		{"security", "Security"},
		{"stagecrew", "Stage Crew"},
		{"crew", "Stage Crew"},
		{"stage", "Stage Crew"},
		{"waiter", "Waiter"},
	} },
	DisguiseKeywords{{eMission::SAPIENZA_THEICON}, {
		{"kitchenstaff", "Kitchen Assistant"},
		{"kitchenassistant", "Kitchen Assistant"},
		{"kitchenass", "Kitchen Assistant"},
		{"kitchensass", "Kitchen Assistant"},
		{"kitchensassistant", "Kitchen Assistant"},
		{"rocco", "Kitchen Assistant"},
		{"moviecrew", "Movie Crew"},
		{"filmcrew", "Movie Crew"},
		{"movie", "Movie Crew"},
		{"security", "Security"},
		{"guard", "Security"},
		{"sfxcrew", "SFX Crew"},
		{"sfx", "SFX Crew"},
	}},
	DisguiseKeywords{{eMission::MARRAKESH_GILDEDCAGE}, {
		{"bodyguard", "Bodyguard"},
		{"camera", "Cameraman"},
		{"cameraman", "Cameraman"},
		{"photographer", "Cameraman"},
		{"consulateintern", "Consulate Intern"},
		{"intern", "Consulate Intern"},
		{"steve", "Consulate Intern"},
		{"hektor", "Consulate Intern"},
		{"lindberg", "Consulate Intern"},
		{"hektorlindberg", "Consulate Intern"},
		{"consulatejanitor", "Consulate Janitor"},
		{"janitor", "Consulate Janitor"},
		{"consulatesecurity", "Consulate Security"},
		{"security", "Consulate Security"},
		{"consulateguard", "Consulate Security"},
		{"elitesoldier", "Elite Soldier"},
		{"elite", "Elite Soldier"},
		{"foodvendor", "Food Vendor"},
		{"vendor", "Food Vendor"},
		{"fortuneteller", "Fortune Teller"},
		{"fortune", "Fortune Teller"},
		{"psychic", "Fortune Teller"},
		{"ft", "Fortune Teller"},
		{"handyman", "Handyman"},
		{"headmaster", "Headmaster"},
		{"teacher", "Headmaster"},
		{"localprintingcrew", "Local Printing Crew"},
		{"printingcrew", "Local Printing Crew"},
		{"printer", "Local Printing Crew"},
		{"printcrew", "Local Printing Crew"},
		{"printing", "Local Printing Crew"},
		{"masseur", "Masseur"},
		{"masseuse", "Masseur"},
		{"massage", "Masseur"},
		{"konnyengstrom", "Masseur"},
		{"konny", "Masseur"},
		{"engstrom", "Masseur"},
		{"militaryofficer", "Military Officer"},
		{"officer", "Military Officer"},
		{"redberet", "Military Officer"},
		{"redhat", "Military Officer"},
		{"militarysoldier", "Military Soldier"},
		{"soldier", "Military Soldier"},
		{"prisoner", "Prisoner"},
		{"shopkeeper", "Shopkeeper"},
		{"shopowner", "Shopkeeper"},
		{"storeowner", "Shopkeeper"},
		{"waiter", "Waiter"},
	}},
	DisguiseKeywords{{eMission::MARRAKESH_HOUSEBUILTONSAND}, {
		{"bodyguard", "Bodyguard"},
		{"foodvendor", "Food Vendor"},
		{"vendor", "Food Vendor"},
		{"fortuneteller", "Fortune Teller"},
		{"fortune", "Fortune Teller"},
		{"psychic", "Fortune Teller"},
		{"ft", "Fortune Teller"},
		{"handyman", "Handyman"},
		{"militarysoldier", "Military Soldier"},
		{"soldier", "Military Soldier"},
		{"shopkeeper", "Shopkeeper"},
		{"shopowner", "Shopkeeper"},
		{"storeowner", "Shopkeeper"},
		{"waiter", "Waiter"},
	}},
	DisguiseKeywords{{eMission::BANGKOK_CLUB27}, {
		{"abeldesilva", "Abel de Silva"},
		{"abel", "Abel de Silva"},
		{"desilva", "Abel de Silva"},
		{"silva", "Abel de Silva"},
		{"exterminator", "Exterminator"},
		{"bugman", "Exterminator"},
		{"groundskeeper", "Groundskeeper"},
		{"gardener", "Groundskeeper"},
		{"hotelsecurity", "Hotel Security"},
		{"security", "Hotel Security"},
		{"hotelguard", "Hotel Security"},
		{"hotelstaff", "Hotel Staff"},
		{"staff", "Hotel Staff"},
		{"jordancrossbodyguard", "Jordan Cross' Bodyguard"},
		{"jordanbodyguard", "Jordan Cross' Bodyguard"},
		{"jcbodyguard", "Jordan Cross' Bodyguard"},
		{"jcguard", "Jordan Cross' Bodyguard"},
		{"jordanguard", "Jordan Cross' Bodyguard"},
		{"jordancrossguard", "Jordan Cross' Bodyguard"},
		{"kitchenstaff", "Kitchen Staff"},
		{"kmbodyguard", "Morgan's Bodyguard"},
		{"kmguard", "Morgan's Bodyguard"},
		{"kmsbodyguard", "Morgan's Bodyguard"},
		{"kmsguard", "Morgan's Bodyguard"},
		{"morgansbodyguard", "Morgan's Bodyguard"},
		{"morgansguard", "Morgan's Bodyguard"},
		{"morganguard", "Morgan's Bodyguard"},
		{"morganbodyguard", "Morgan's Bodyguard"},
		{"kensbodyguard", "Morgan's Bodyguard"},
		{"kensguard", "Morgan's Bodyguard"},
		{"kenguard", "Morgan's Bodyguard"},
		{"kenbodyguard", "Morgan's Bodyguard"},
		{"otis", "Morgan's Bodyguard"},
		{"recordingcrew", "Recording Crew"},
		{"recording", "Recording Crew"},
		{"crew", "Recording Crew"},
		{"band", "Recording Crew"},
		{"stage", "Recording Crew"},
		{"roadie", "Recording Crew"},
		{"stalker", "Stalker"},
		{"stalk", "Stalker"},
		{"creep", "Stalker"},
		{"waiter", "Waiter"},
	}},
	DisguiseKeywords{{eMission::BANGKOK_THESOURCE}, {
		{"cultbodyguard", "Cult Bodyguard"},
		{"cultguard", "Cult Bodyguard"},
		{"cultinitiate", "Cult Initiate"},
		{"initiate", "Cult Initiate"},
		{"gardener", "Groundskeeper"},
		{"groundskeeper", "Groundskeeper"},
		{"exterminator", "Exterminator"},
		{"bugman", "Exterminator"},
		{"hotelsecurity", "Hotel Security"},
		{"security", "Hotel Security"},
		{"hotelguard", "Hotel Security"},
		{"hotelstaff", "Hotel Staff"},
		{"staff", "Hotel Staff"},
		{"jordancrossbodyguard", "Jordan Cross' Bodyguard"},
		{"jordanbodyguard", "Jordan Cross' Bodyguard"},
		{"jcbodyguard", "Jordan Cross' Bodyguard"},
		{"jcguard", "Jordan Cross' Bodyguard"},
		{"jordanguard", "Jordan Cross' Bodyguard"},
		{"jordancrossguard", "Jordan Cross' Bodyguard"},
		{"kitchenstaff", "Kitchen Staff"},
		{"kitchen", "Kitchen Staff"},
		{"militiasoldier", "Militia Soldier"},
		{"militia", "Militia Soldier"},
		{"military", "Militia Soldier"},
		{"soldier", "Militia Soldier"},
		{"recordingcrew", "Recording Crew"},
		{"recording", "Recording Crew"},
		{"crew", "Recording Crew"},
		{"band", "Recording Crew"},
		{"stage", "Recording Crew"},
		{"roadie", "Recording Crew"},
		{"waiter", "Waiter"},
	}},
	DisguiseKeywords{{eMission::COLORADO_FREEDOMFIGHTERS}, {
		{"explosivesspecialist", "Explosives Specialist"},
		{"explosivespecialist", "Explosives Specialist"},
		{"explosivespec", "Explosives Specialist"},
		{"explosives", "Explosives Specialist"},
		{"hacker", "Hacker"},
		{"militiacook", "Militia Cook"},
		{"cook", "Militia Cook"},
		{"chef", "Militia Cook"},
		{"militiaelite", "Militia Elite"},
		{"elite", "Militia Elite"},
		{"militiasoldier", "Militia Soldier"},
		{"soldier", "Militia Soldier"},
		{"militiaspecops", "Militia Spec Ops"},
		{"militiaspec", "Militia Soldier"},
		{"specops", "Militia Soldier"},
		{"specialops", "Militia Soldier"},
		{"militiatechnician", "Militia Technician"},
		{"militiatech", "Militia Technician"},
		{"technician", "Militia Technician"},
		{"tech", "Militia Technician"},
		{"pointman", "Point Man"},
		{"burges", "Point Man"},
		{"point", "Point Man"},
		{"scarecrow", "Scarecrow"},
	}},
	DisguiseKeywords{{eMission::HOKKAIDO_SITUSINVERSUS, eMission::HOKKAIDO_SNOWFESTIVAL}, {
		{"baseballplayer", "Baseball Player"},
		{"baseball", "Baseball Player"},
		{"baseboi", "Baseball Player"},
		{"bodyguard", "Bodyguard"},
		{"chef", "Chef"},
		{"chiefsurgeon", "Chief Surgeon"},
		{"chief", "Chief Surgeon"},
		{"chiefy", "Chief Surgeon"},
		{"laurant", "Chief Surgeon"},
		{"doctor", "Doctor"},
		{"dr", "Doctor"},
		{"doc", "Doctor"},
		{"handyman", "Handyman"},
		{"gardener", "Handyman"},
		{"repairman", "Handyman"},
		{"helicopterpilot", "Helicopter Pilot"},
		{"helicopter", "Helicopter Pilot"},
		{"pilot", "Helicopter Pilot"},
		{"hospitaldirector", "Hospital Director"},
		{"director", "Hospital Director"},
		{"morguedoctor", "Morgue Doctor"},
		{"morgue", "Morgue Doctor"},
		{"morguedr", "Morgue Doctor"},
		{"motorcyclist", "Motorcyclist"},
		{"motorcycle", "Motorcyclist"},
		{"ninja", "Ninja"},
		{"patient", "Patient"},
		{"resortsecurity", "Resort Security"},
		{"security", "Resort Security"},
		{"resortguard", "Resort Security"},
		{"guard", "Resort Security"},
		{"resortstaff", "Resort Staff"},
		{"staff", "Resort Staff"},
		{"surgeon", "Surgeon"},
		{"vippatientamosdexter", "VIP Patient (Amos Dexter)"},
		{"vippatientamos", "VIP Patient (Amos Dexter)"},
		{"vippatientdexter", "VIP Patient (Amos Dexter)"},
		{"patientamosdexter", "VIP Patient (Amos Dexter)"},
		{"patientdexter", "VIP Patient (Amos Dexter)"},
		{"patientamos", "VIP Patient (Amos Dexter)"},
		{"amosdexter", "VIP Patient (Amos Dexter)"},
		{"amos", "VIP Patient (Amos Dexter)"},
		{"dexter", "VIP Patient (Amos Dexter)"},
		{"jasonportman", "VIP Patient (Jason Portman)"},
		{"vippatientjasonportman", "VIP Patient (Jason Portman)"},
		{"patientjasonportman", "VIP Patient (Jason Portman)"},
		{"patientjason", "VIP Patient (Jason Portman)"},
		{"patientportman", "VIP Patient (Jason Portman)"},
		{"vippatientjason", "VIP Patient (Jason Portman)"},
		{"vippatientportman", "VIP Patient (Jason Portman)"},
		{"jason", "VIP Patient (Jason Portman)"},
		{"portman", "VIP Patient (Jason Portman)"},
		{"yogainstructor", "Yoga Instructor"},
		{"yoga", "Yoga Instructor"},
	}},
	DisguiseKeywords{{eMission::HOKKAIDO_PATIENTZERO}, {
		{"biosuit", "Bio Suit"},
		{"hazmatsuit", "Bio Suit"},
		{"biohazardsuit", "Bio Suit"},
		{"hazardsuit", "Bio Suit"},
		{"bodyguard", "Bodyguard"},
		{"chef", "Chef"},
		{"doctor", "Doctor"},
		{"dr", "Doctor"},
		{"doc", "Doctor"},
		{"handyman", "Handyman"},
		{"gardener", "Handyman"},
		{"repairman", "Handyman"},
		{"headresearcher", "Head Researcher"},
		{"researcher", "Head Researcher"},
		{"helicopterpilot", "Helicopter Pilot"},
		{"helicopter", "Helicopter Pilot"},
		{"pilot", "Helicopter Pilot"},
		{"hospitaldirector", "Hospital Director"},
		{"director", "Hospital Director"},
		{"morguedoctor", "Morgue Doctor"},
		{"morgue", "Morgue Doctor"},
		{"morguedr", "Morgue Doctor"},
		{"motorcyclist", "Motorcyclist"},
		{"motorcycle", "Motorcyclist"},
		{"patient", "Patient"},
		{"resortsecurity", "Resort Security"},
		{"security", "Resort Security"},
		{"resortguard", "Resort Security"},
		{"guard", "Resort Security"},
		{"resortstaff", "Resort Staff"},
		{"staff", "Resort Staff"},
		{"surgeon", "Surgeon"},
		{"amosdexter", "VIP Patient (Amos Dexter)"},
		{"amos", "VIP Patient (Amos Dexter)"},
		{"dexter", "VIP Patient (Amos Dexter)"},
		{"yogainstructor", "Yoga Instructor"},
		{"yoga", "Yoga Instructor"},
	}},
	DisguiseKeywords{{eMission::HAWKESBAY_NIGHTCALL}, {
		{"bodyguard", "Bodyguard"},
		{"guard", "Bodyguard"},
	}},
	DisguiseKeywords{{eMission::MIAMI_FINISHLINE, eMission::MIAMI_ASILVERTONGUE}, {
		{"aeondriver", "Aeon Driver"},
		{"aeonmechanic", "Aeon Mechanic"},
		{"blueseeddriver", "Blue Seed Driver"},
		{"blueseed", "Blue Seed Driver"},
		{"crashedkronstadtdriver", "Crashed Kronstadt Driver"},
		{"crasheddriver", "Crashed Kronstadt Driver"},
		{"crashed", "Crashed Kronstadt Driver"},
		{"eventcrew", "Event Crew"},
		{"crew", "Event Crew"},
		{"eventstaff", "Event Crew"},
		{"eventsecurity", "Event Security"},
		{"security", "Event Security"},
		{"cop", "Event Security"},
		{"floridaman", "Florida Man"},
		{"flman", "Florida Man"},
		{"florida", "Florida Man"},
		{"foodvendor", "Food Vendor"},
		{"vendor", "Food Vendor"},
		{"journalist", "Journalist"},
		{"press", "Journalist"},
		{"paparazzi", "Journalist"},
		{"kitchenstaff", "Kitchen Staff"},
		{"kitchen", "Kitchen Staff"},
		{"kowoondriver", "Kowoon Driver"},
		{"kowoonmechanic", "Kowoon Mechanic"},
		{"kronstadtengineer", "Kronstadt Engineer"},
		{"engineer", "Kronstadt Engineer"},
		{"kronstadtmechanic", "Kronstadt Mechanic"},
		{"kronstadtresearcher", "Kronstadt Researcher"},
		{"researcher", "Kronstadt Researcher"},
		{"research", "Kronstadt Researcher"},
		{"kronstadtsecurity", "Kronstadt Security"},
		{"kronstadtguard", "Kronstadt Security"},
		{"bodyguard", "Kronstadt Security"},
		{"robertguard", "Kronstadt Security"},
		{"robertsecurity", "Kronstadt Security"},
		{"mascot", "Mascot"},
		{"medic", "Medic"},
		{"moseslee", "Moses Lee"},
		{"palerider", "Pale Rider"},
		{"pale", "Pale Rider"},
		{"thestig", "Pale Rider"},
		{"stig", "Pale Rider"},
		{"racecoordinator", "Race Coordinator"},
		{"racecoord", "Race Coordinator"},
		{"coordinator", "Race Coordinator"},
		{"coord", "Race Coordinator"},
		{"racemarshal", "Race Marshal"},
		{"racemarshall", "Race Marshal"},
		{"marshal", "Race Marshal"},
		{"marshall", "Race Marshal"},
		{"sheikh", "Sheik"},
		{"sotteraneomechanic", "Sotteraneo Mechanic"},
		{"sotteraneo", "Sotteraneo Mechanic"},
		{"streetmusician", "Street Musician"},
		{"musician", "Street Musician"},
		{"streetperformer", "Street Musician"},
		{"performer", "Street Musician"},
		{"drum", "Street Musician"},
		{"drummer", "Street Musician"},
		{"tedmendez", "Ted Mendez"},
		{"ted", "Ted Mendez"},
		{"mendez", "Ted Mendez"},
		{"military", "Ted Mendez"},
		{"thwackdriver", "Thwack Driver"},
		{"thwackmechanic", "Thwack Mechanic"},
		{"waiter", "Waiter"},
	}},
	DisguiseKeywords{{eMission::SANTAFORTUNA_THREEHEADEDSERPENT, eMission::SANTAFORTUNA_EMBRACEOFTHESERPENT}, {
		{"bandmember", "Band Member"},
		{"band", "Band Member"},
		{"drummer", "Band Member"},
		{"drum", "Band Member"},
		{"barman", "Barman"},
		{"bartender", "Barman"},
		{"bar", "Barman"},
		{"chef", "Chef"},
		{"cocafieldguard", "Coca Field Guard"},
		{"cocaguard", "Coca Field Guard"},
		{"fieldguard", "Coca Field Guard"},
		{"jorgeguard", "Coca Field Guard"},
		{"cocafieldworker", "Coca Field Worker"},
		{"cocaworker", "Coca Field Worker"},
		{"fieldworker", "Coca Field Worker"},
		{"constructionworker", "Construction Worker"},
		{"construction", "Construction Worker"},
		{"builder", "Construction Worker"},
		{"druglabworker", "Drug Lab Worker"},
		{"drugworker", "Drug Lab Worker"},
		{"labworker", "Drug Lab Worker"},
		{"druglab", "Drug Lab Worker"},
		{"lab", "Drug Lab Worker"},
		{"eliteguard", "Elite Guard"},
		{"elite", "Elite Guard"},
		{"gardener", "Gardener"},
		{"hippie", "Hippie"},
		{"bohemian", "Hippie"},
		{"hippowhisperer", "Hippo Whisperer"},
		{"hippo", "Hippo Whisperer"},
		{"whisperer", "Hippo Whisperer"},
		{"mansionguard", "Mansion Guard"},
		{"manguard", "Mansion Guard"},
		{"mansionsecurity", "Mansion Guard"},
		{"mansionstaff", "Mansion Staff"},
		{"staff", "Mansion Staff"},
		{"servant", "Mansion Staff"},
		{"shaman", "Shaman"},
		{"taita", "Shaman"},
		{"streetsoldier", "Street Soldier"},
		{"soldier", "Street Soldier"},
		{"streetguard", "Street Soldier"},
		{"submarinecrew", "Submarine Crew"},
		{"subcrew", "Submarine Crew"},
		{"submarineworker", "Submarine Crew"},
		{"submarine", "Submarine Crew"},
		{"submarineengineer", "Submarine Engineer"},
		{"subengineer", "Submarine Engineer"},
		{"engineer", "Submarine Engineer"},
		{"tattooartist", "Tattoo Artist (P-Power)"},
		{"tattooartistppower", "Tattoo Artist (P-Power)"},
		{"tattooartistp", "Tattoo Artist (P-Power)"},
		{"artistppower", "Tattoo Artist (P-Power)"},
		{"ppower", "Tattoo Artist (P-Power)"},
		{"paulpowers", "Tattoo Artist (P-Power)"},
		{"puhpower", "Tattoo Artist (P-Power)"},
		{"power", "Tattoo Artist (P-Power)"},
	}},
	DisguiseKeywords{{eMission::MUMBAI_CHASINGAGHOST, eMission::MUMBAI_ILLUSIONSOFGRANDEUR}, {
		{"barber", "Barber"},
		{"barbershop", "Barber"},
		{"bollywoodbodyguard", "Bollywood Bodyguard"},
		{"bollywoodguard", "Bollywood Bodyguard"},
		{"bollywoodcrew", "Bollywood Crew"},
		{"crew", "Bollywood Crew"},
		{"dancer", "Dancer"},
		{"dance", "Dancer"},
		{"elitethug", "Elite Thug"},
		{"elite", "Elite Thug"},
		{"foodvendor", "Food Vendor"},
		{"vendor", "Food Vendor"},
		{"holyman", "Holy Man"},
		{"holy", "Holy Man"},
		{"kashmirian", "Kashmirian"},
		{"assassin", "Kashmirian"},
		{"laundryforeman", "Laundry Foreman"},
		{"foreman", "Laundry Foreman"},
		{"laundryworker", "Laundry Worker"},
		{"leadactor", "Lead Actor"},
		{"actor", "Lead Actor"},
		{"gregoryarthur", "Lead Actor"},
		{"gregory", "Lead Actor"},
		{"localsecurity", "Local Security"},
		{"security", "Local Security"},
		{"metalworker", "Metal Worker"},
		{"metal", "Metal Worker"},
		{"forger", "Metal Worker"},
		{"painter", "Painter"},
		{"paint", "Painter"},
		{"artist", "Painter"},
		{"queensbodyguard", "Queen's Bodyguard"},
		{"queenbodyguard", "Queen's Bodyguard"},
		{"vanyabodyguard", "Queen's Bodyguard"},
		{"vanyasbodyguard", "Queen's Bodyguard"},
		{"queensguard", "Queen's Guard"},
		{"queenguard", "Queen's Guard"},
		{"vanyaguard", "Queen's Guard"},
		{"vanyasguard", "Queen's Guard"},
		{"tailor", "Tailor"},
		{"thug", "Thug"},
		{"vanyasservant", "Vanya's Servant"},
		{"vanyaservant", "Vanya's Servant"},
	}},
	DisguiseKeywords{{eMission::WHITTLETON_ANOTHERLIFE, eMission::WHITTLETON_ABITTERPILL}, {
		{"arkianrobes", "Arkian Robes"},
		{"arkrobes", "Arkian Robes"},
		{"arkiantux", "Arkian Robes"},
		{"arkian", "Arkian Robes"},
		{"tux", "Arkian Robes"},
		{"robes", "Arkian Robes"},
		{"bbqowner", "BBQ Owner"},
		{"bbq", "BBQ Owner"},
		{"richard", "BBQ Owner"},
		{"cassidybodyguard", "Cassidy Bodyguard"},
		{"cassidysbodyguard", "Cassidy Bodyguard"},
		{"nolanbodyguard", "Cassidy Bodyguard"},
		{"ncbodyguard", "Cassidy Bodyguard"},
		{"nolanguard", "Cassidy Bodyguard"},
		{"cassidyguard", "Cassidy Bodyguard"},
		{"constructionworker", "Construction Worker"},
		{"construction", "Construction Worker"},
		{"builder", "Construction Worker"},
		{"exterminator", "Exterminator"},
		{"bugman", "Exterminator"},
		{"pestcontrol", "Exterminator"},
		{"garbageman", "Garbage Man"},
		{"garbage", "Garbage Man"},
		{"bin", "Garbage Man"},
		{"gardener", "Gardener"},
		{"gunthermueller", "Gunther Mueller"},
		{"gunther", "Gunther Mueller"},
		{"mueller", "Gunther Mueller"},
		{"jamesbatty", "James Batty"},
		{"batty", "James Batty"},
		{"james", "James Batty"},
		{"janusbodyguard", "Janus' Bodyguard"},
		{"janusguard", "Janus' Bodyguard"},
		{"mailman", "Mailman"},
		{"mail", "Mailman"},
		{"deliveryman", "Mailman"},
		{"delivery", "Mailman"},
		{"nurse", "Nurse"},
		{"plumber", "Plumber"},
		{"policedeputy", "Police Deputy"},
		{"deputy", "Police Deputy"},
		{"police", "Police Deputy"},
		{"cop", "Police Deputy"},
		{"politician", "Politician"},
		{"politiciansassistant", "Politician's Assistant"},
		{"politicianassistant", "Politician's Assistant"},
		{"politiciansass", "Politician's Assistant"},
		{"politicianass", "Politician's Assistant"},
		{"politicassistant", "Politician's Assistant"},
		{"pa", "Politician's Assistant"},
		{"realestatebroker", "Real Estate Broker"},
		{"realestateagent", "Real Estate Broker"},
		{"estateagent", "Real Estate Broker"},
		{"realestate", "Real Estate Broker"},
		{"server", "Server"},
		{"sheriffmasterson", "Sheriff Masterson"},
		{"sheriff", "Sheriff Masterson"},
		{"masterson", "Sheriff Masterson"},
		{"spencergreen", "Spencer \"The Hammer\" Green"},
		{"thehammergreen", "Spencer \"The Hammer\" Green"},
		{"spencerthehammer", "Spencer \"The Hammer\" Green"},
		{"spencerhammergreen", "Spencer \"The Hammer\" Green"},
		{"thehammer", "Spencer \"The Hammer\" Green"},
		{"spencer", "Spencer \"The Hammer\" Green"},
		{"hammer", "Spencer \"The Hammer\" Green"},
		{"green", "Spencer \"The Hammer\" Green"},
	}},
	DisguiseKeywords{{eMission::ISLEOFSGAIL_THEARKSOCIETY}, {
		{"architect", "Architect"},
		{"arkitect", "Architect"},
		{"arkmember", "Ark Member"},
		{"arkian", "Ark Member"},
		{"member", "Ark Member"},
		{"blakenathaniel", "Blake Nathaniel"},
		{"blake", "Blake Nathaniel"},
		{"nathaniel", "Blake Nathaniel"},
		{"burialrobes", "Burial Robes"},
		{"burialoutfit", "Burial Robes"},
		{"burial", "Burial Robes"},
		{"robes", "Burial Robes"},
		{"janus", "Burial Robes"},
		{"butler", "Butler"},
		{"castlestaff", "Castle Staff"},
		{"castle", "Castle Staff"},
		{"chef", "Chef"},
		{"custodian", "Custodian"},
		{"eliteguard", "Elite Guard"},
		{"elite", "Elite Guard"},
		{"entertainer", "Entertainer"},
		{"eventstaff", "Event Staff"},
		{"event", "Event Staff"},
		{"guard", "Guard"},
		{"initiate", "Initiate"},
		{"jebediahblock", "Jebediah Block"},
		{"jebediah", "Jebediah Block"},
		{"jebidiah", "Jebediah Block"},
		{"block", "Jebediah Block"},
		{"jeb", "Jebediah Block"},
		{"kightsarmor", "Knight's Armor"},
		{"kightarmor", "Knight's Armor"},
		{"kight", "Knight's Armor"},
		{"armor", "Knight's Armor"},
		{"masterofceremonies", "Master of Ceremonies"},
		{"master", "Master of Ceremonies"},
		{"ceremonies", "Master of Ceremonies"},
		{"moc", "Master of Ceremonies"},
		{"raider", "Raider"},
	}},
	DisguiseKeywords{{eMission::NEWYORK_GOLDENHANDSHAKE}, {
		{"bankrobber", "Bank Robber"},
		{"robber", "Bank Robber"},
		{"burglar", "Bank Robber"},
		{"bankteller", "Bank Teller"},
		{"teller", "Bank Teller"},
		{"firedbanker", "Fired Banker"},
		{"fired", "Fired Banker"},
		{"highsecurityguard", "High Security Guard"},
		{"highsecurity", "High Security Guard"},
		{"highguard", "High Security Guard"},
		{"investmentbanker", "Investment Banker"},
		{"investment", "Investment Banker"},
		{"itworker", "IT Worker"},
		{"it", "IT Worker"},
		{"janitor", "Janitor"},
		{"jobapplicant", "Job Applicant"},
		{"applicant", "Job Applicant"},
		{"securityguard", "Security Guard"},
		{"security", "Security Guard"},
		{"guard", "Security Guard"},
	}},
	DisguiseKeywords{{eMission::HAVEN_THELASTRESORT}, {
		{"boatcaptain", "Boat Captain"},
		{"boat", "Boat Captain"},
		{"captain", "Boat Captain"},
		{"bodyguard", "Bodyguard"},
		{"butler", "Butler"},
		{"chef", "Chef"},
		{"doctor", "Doctor"},
		{"gassuit", "Gas Suit"},
		{"gas", "Gas Suit"},
		{"boilersuit", "Gas Suit"},
		{"boiler", "Gas Suit"},
		{"lifeguard", "Life Guard"},
		{"life", "Life Guard"},
		{"masseur", "Masseur"},
		{"personaltrainer", "Personal Trainer"},
		{"gymtrainer", "Personal Trainer"},
		{"trainer", "Personal Trainer"},
		{"gym", "Personal Trainer"},
		{"coach", "Personal Trainer"},
		{"resortguard", "Resort Guard"},
		{"resortstaff", "Resort Staff"},
		{"snorkelinstructor", "Snorkel Instructor"},
		{"snorkel", "Snorkel Instructor"},
		{"cj", "Snorkel Instructor"},
		{"scuba", "Snorkel Instructor"},
		{"techcrew", "Tech Crew"},
		{"tech", "Tech Crew"},
		{"crew", "Tech Crew"},
		{"villaguard", "Villa Guard"},
		{"mansionguard", "Villa Guard"},
		{"villastaff", "Villa Staff"},
		{"mansionstaff", "Villa Staff"},
		{"waiter", "Waiter"},
	}},
	DisguiseKeywords{{eMission::DUBAI_ONTOPOFTHEWORLD}, {
		{"artcrew", "Art Crew"},
		{"art", "Art Crew"},
		{"crew", "Art Crew"},
		{"eventsecurity", "Event Security"},
		{"security", "Event Security"},
		{"eventstaff", "Event Staff"},
		{"staff", "Event Staff"},
		{"famouschef", "Famous Chef"},
		{"chef", "Famous Chef"},
		{"famous", "Famous Chef"},
		{"helicopterpilot", "Helicopter Pilot"},
		{"helicopter", "Helicopter Pilot"},
		{"pilot", "Helicopter Pilot"},
		{"ingramsbodyguard", "Ingram's Bodyguard"},
		{"bodyguard", "Ingram's Bodyguard"},
		{"ingrambodyguard", "Ingram's Bodyguard"},
		{"carlbodyguard", "Ingram's Bodyguard"},
		{"carlguard", "Ingram's Bodyguard"},
		{"carlsguard", "Ingram's Bodyguard"},
		{"carlsbodyguard", "Ingram's Bodyguard"},
		{"cibodyguard", "Ingram's Bodyguard"},
		{"ciguard", "Ingram's Bodyguard"},
		{"kitchenstaff", "Kitchen Staff"},
		{"kitchen", "Kitchen Staff"},
		{"maintenancestaff", "Maintenance Staff"},
		{"maintenance", "Maintenance Staff"},
		{"penthouseguard", "Penthouse Guard"},
		{"penthouse", "Penthouse Guard"},
		{"penthousestaff", "Penthouse Staff"},
		{"skydivingsuit", "Skydiving Suit"},
		{"skydiving", "Skydiving Suit"},
		{"divingsuit", "Skydiving Suit"},
		{"diving", "Skydiving Suit"},
		{"theassassin", "The Assassin"},
		{"assassin", "The Assassin"},
	}},
	DisguiseKeywords{{eMission::DARTMOOR_DEATHINTHEFAMILY}, {
		{"bodyguard", "Bodyguard"},
		{"gardener", "Gardener"},
		{"lawyer", "Lawyer"},
		{"mansionguard", "Mansion Guard"},
		{"guard", "Mansion Guard"},
		{"mansionstaff", "Mansion Staff"},
		{"staff", "Mansion Staff"},
		{"photographer", "Photographer"},
		{"photo", "Photographer"},
		{"cameraman", "Photographer"},
		{"camera", "Photographer"},
		{"privateinvestigator", "Private Investigator"},
		{"investigator", "Private Investigator"},
		{"privatedetective", "Private Investigator"},
		{"detective", "Private Investigator"},
		{"phinas", "Private Investigator"},
		{"pi", "Private Investigator"},
		{"pd", "Private Investigator"},
		{"undertaker", "Undertaker"},
		{"funeral", "Undertaker"},
	}},
	DisguiseKeywords{{eMission::BERLIN_APEXPREDATOR}, {
		{"bartender", "Bartender"},
		{"bar", "Bartender"},
		{"biker", "Biker"},
		{"clubcrew", "Club Crew"},
		{"crew", "Club Crew"},
		{"clubsecurity", "Club Security"},
		{"security", "Club Security"},
		{"dealer", "Dealer"},
		{"drug", "Dealer"},
		{"deliveryguy", "Delivery Guy"},
		{"delivery", "Delivery Guy"},
		{"dj", "DJ"},
		{"diskjockey", "DJ"},
		{"floridaman", "Florida Man"},
		{"florida", "Florida Man"},
		{"flman", "Florida Man"},
		{"rolfhirschmuller", "Rolf Hirschmüller"s},
		{"rolf", "Rolf Hirschmüller"s},
		{"hirschmuller", "Rolf Hirschmüller"s},
		{"technician", "Technician"},
		{"tech", "Technician"},
	}},
	DisguiseKeywords{{eMission::CHONGQING_ENDOFANERA}, {
		{"blockguard", "Block Guard"},
		{"dumplingcook", "Dumpling Cook"},
		{"dumpling", "Dumpling Cook"},
		{"cook", "Dumpling Cook"},
		{"dumplincook", "Dumpling Cook"},
		{"facilityanalyst", "Facility Analyst"},
		{"analyst", "Facility Analyst"},
		{"facilityengineer", "Facility Engineer"},
		{"engineer", "Facility Engineer"},
		{"facilityguard", "Facility Guard"},
		{"facilitysecurity", "Facility Security"},
		{"security", "Facility Security"},
		{"homelessperson", "Homeless Person"},
		{"homeless", "Homeless Person"},
		{"person", "Homeless Person"},
		{"hobo", "Homeless Person"},
		{"bum", "Homeless Person"},
		{"perfecttestsubject", "Perfect Test Subject"},
		{"perfecttest", "Perfect Test Subject"},
		{"testsubject", "Perfect Test Subject"},
		{"perfectsubject", "Perfect Test Subject"},
		{"perfect", "Perfect Test Subject"},
		{"test", "Perfect Test Subject"},
		{"subject", "Perfect Test Subject"},
		{"researcher", "Researcher"},
		{"research", "Researcher"},
		{"streetguard", "Street Guard"},
		{"street", "Street Guard"},
		{"guard", "Street Guard"},
		{"theboardmember", "The Board Member"},
		{"boardmember", "The Board Member"},
		{"board", "The Board Member"},
		{"member", "The Board Member"},
		{"mrpritchard", "The Board Member"},
		{"pritchard", "The Board Member"},
	}},
	DisguiseKeywords{{eMission::MENDOZA_THEFAREWELL}, {
		{"asadochef", "Asado Chef"},
		{"asado", "Asado Chef"},
		{"chef", "Asado Chef"},
		{"bodyguard", "Bodyguard"},
		{"guard", "Bodyguard"},
		{"chiefwinemaker", "Chief Winemaker"},
		{"chief", "Chief Winemaker"},
		{"gabrielvargas", "Chief Winemaker"},
		{"vargas", "Chief Winemaker"},
		{"gabriel", "Chief Winemaker"},
		{"winemaker", "Chief Winemaker"},
		{"cw", "Chief Winemaker"},
		{"corvoblack", "Corvo Black"},
		{"corvo", "Corvo Black"},
		{"black", "Corvo Black"},
		{"gaucho", "Gaucho"},
		{"headofsecurity", "Head of Security"},
		{"hos", "Head of Security"},
		{"head", "Head of Security"},
		{"juancortazar", "Head of Security"},
		{"cortazar", "Head of Security"},
		{"lawyer", "Lawyer"},
		{"law", "Lawyer"},
		{"mercenary", "Mercenary"},
		{"merc", "Mercenary"},
		{"providenceherald", "Providence Herald"},
		{"providence", "Providence Herald"},
		{"herald", "Providence Herald"},
		{"sommelier", "Sommelier"},
		{"tangomusician", "Tango Musician"},
		{"tango", "Tango Musician"},
		{"musician", "Tango Musician"},
		{"waiter", "Waiter"},
		{"wineryworker", "Winery Worker"},
		{"winery", "Winery Worker"},
		{"worker", "Winery Worker"},
	}},
	DisguiseKeywords{{eMission::CARPATHIAN_UNTOUCHABLE}, {
		{"officestaff", "Office Staff"},
		{"office", "Office Staff"},
		{"staff", "Office Staff"},
		{"providencecommando", "Providence Commando"},
		{"commando", "Providence Commando"},
		{"providencecommandoleader", "Providence Commando Leader"},
		{"commandoleader", "Providence Commando Leader"},
		{"providencedoctor", "Providence Doctor"},
		{"doctor", "Providence Doctor"},
		{"providenceeliteguard", "Providence Elite Guard"},
		{"eliteguard", "Providence Elite Guard"},
		{"elite", "Providence Elite Guard"},
		{"militiazone", "Providence Security Guard (Militia Zone)"},
		{"militia", "Providence Security Guard (Militia Zone)"},
		{"securityguardoffice", "Providence Security Guard (Office)"},
		{"guardoffice", "Providence Security Guard (Office)"},
		{"officeguard", "Providence Security Guard (Office)"},
	}},
	DisguiseKeywords{{eMission::AMBROSE_SHADOWSINTHEWATER}, {
		{"cook", "Cook"},
		{"engineer", "Engineer"},
		{"hippie", "Hippie"},
		{"metalworker", "Metal Worker"},
		{"metal", "Metal Worker"},
		{"worker", "Metal Worker"},
		{"militiasoldier", "Militia Soldier"},
		{"militia", "Militia Soldier"},
		{"soldier", "Militia Soldier"},
		{"pirate", "Pirate"},
	}},
};
const std::unordered_map<std::string, std::string> methodKeywords = {
	{"amputation", "Amputation Knife"},
	{"ampknife", "Amputation Knife"},
	{"amputationknife", "Amputation Knife"},
	{"antiquecurvedknife", "Antique Curved Knife"},
	{"antiquecurveknife", "Antique Curved Knife"},
	{"antiqueknife", "Antique Curved Knife"},
	{"curvedknife", "Antique Curved Knife"},
	{"curveknife", "Antique Curved Knife"},
	{"acknife", "Antique Curved Knife"},
	{"barberrazor", "Barber Razor"},
	{"razor", "Barber Razor"},
	{"battleaxe", "Battle Axe"},
	{"bataxe", "Battle Axe"},
	{"baxe", "Battle Axe"},
	{"beakstaff", "Beak Staff"},
	{"broadsword", "Broadsword"},
	{"burialknife", "Burial Knife"},
	{"burialdagger", "Burial Knife"},
	{"circumcision", "Circumcision Knife"},
	{"circumcisionknife", "Circumcision Knife"},
	{"circknife", "Circumcision Knife"},
	{"cleaver", "Cleaver"},
	{"meatcleaver", "Cleaver"},
	{"combatknife", "Combat Knife"},
	{"concealknife", "Concealable Knife"},
	{"concealableknife", "Concealable Knife"},
	{"fireaxe", "Fire Axe"},
	{"foldingknife", "Folding Knife"},
	{"foldknife", "Folding Knife"},
	{"gardenfork", "Garden Fork"},
	{"grapeknife", "Grape Knife"},
	{"hatchet", "Hatchet"},
	{"hobby", "Hobby Knife"},
	{"hobbyknife", "Hobby Knife"},
	{"boxcutter", "Hobby Knife"},
	{"holidayfireaxe", "Holiday Fire Axe"},
	{"festivefireaxe", "Holiday Fire Axe"},
	{"christmasfireaxe", "Holiday Fire Axe"},
	{"xmasfireaxe", "Holiday Fire Axe"},
	{"hook", "Hook"},
	{"icicle", "Icicle"},
	{"ice", "Icicle"},
	{"jarlspiratesaber", "Jarl's Pirate Saber"},
	{"piratesaber", "Jarl's Pirate Saber"},
	{"jarlssaber", "Jarl's Pirate Saber"},
	{"piratesword", "Jarl's Pirate Saber"},
	{"jarlspiratesword", "Jarl's Pirate Saber"},
	{"jarlssword", "Jarl's Pirate Saber"},
	{"katana", "Katana"},
	{"katanasword", "Katana"},
	{"kitchenknife", "Kitchen Knife"},
	{"kknife", "Kitchen Knife"},
	{"knife", "Kitchen Knife"},
	{"kukrimachete", "Kukri Machete"},
	{"kukri", "Kukri Machete"},
	{"letteropener", "Letter Opener"},
	{"letopener", "Letter Opener"},
	{"machete", "Machete"},
	{"meatfork", "Meat Fork"},
	{"fork", "Meat Fork"},
	{"oldaxe", "Old Axe"},
	{"ornatescimitar", "Ornate Scimitar"},
	{"ornate", "Ornate Scimitar"},
	{"scimitar", "Ornate Scimitar"},
	{"rustyscrewdriver", "Rusty Screwdriver"},
	{"rustedscrewdriver", "Rusty Screwdriver"},
	{"rustscrewdriver", "Rusty Screwdriver"},
	{"saber", "Saber"},
	{"sacknife", "Sacrificial Knife"},
	{"sacrificial", "Sacrificial Knife"},
	{"sacrificialknife", "Sacrificial Knife"},
	{"sappersaxe", "Sapper's Axe"},
	{"sappers", "Sapper's Axe"},
	{"sapperaxe", "Sapper's Axe"},
	{"sapaxe", "Sapper's Axe"},
	{"scalpel", "Scalpel"},
	{"scissors", "Scissors"},
	{"scissor", "Scissors"},
	{"scrapsword", "Scrap Sword"},
	{"scrap", "Scrap Sword"},
	{"screwdriver", "Screwdriver"},
	{"seashell", "Seashell"},
	{"shell", "Seashell"},
	{"shears", "Shears"},
	{"shear", "Shears"},
	{"shuriken", "Shuriken"},
	{"ninjastar", "Shuriken"},
	{"throwingstar", "Shuriken"},
	{"electrocution", "Electrocution"},
	{"electro", "Electrocution"},
	{"electrocute", "Electrocution"},
	{"elec", "Electrocution"},
	{"electricity", "Electrocution"},
	{"electric", "Electrocution"},
	{"zap", "Electrocution"},
	{"explosion", "Explosion"},
	{"explosive", "Explosion"},
	{"stemcells", "Poison Stem Cells"},
	{"poisonstemcells", "Poison Stem Cells"},
	{"poison", "Poison Stem Cells"},
	{"poisoncells", "Poison Stem Cells"},
	{"robotarms", "Robot Arms"},
	{"arms", "Robot Arms"},
	{"robot", "Robot Arms"},
	{"kai", "Robot Arms"},
	{"shootheart", "Shoot Heart"},
	{"shoottheheart", "Shoot Heart"},
	{"heartshot", "Shoot Heart"},
	{"trashheart", "Trash Heart"},
	{"trashcan", "Trash Heart"},
	{"throwheart", "Trash Heart"},
	{"trash", "Trash Heart"},
	{"throwheartinthetrash", "Trash Heart"},
	{"throwtheheartinthetrash", "Trash Heart"},
	{"throwheartintrash", "Trash Heart"},
	{"starfish", "Starfish"},
	{"tanto", "Tanto"},
	{"unicornhorn", "Unicorn Horn"},
	{"unicorn", "Unicorn Horn"},
	{"vikingaxe", "Viking Axe"},
	{"viking", "Viking Axe"},
	{"xmasstar", "Xmas Star"},
	{"christmasstar", "Xmas Star"},
	{"festivestar", "Xmas Star"},
};
const std::unordered_map<std::string, eKillComplication> complicationKeywords = {
	{"live", eKillComplication::Live},
	{"nko", eKillComplication::Live},
	{"noko", eKillComplication::Live},
	{"nonko", eKillComplication::Live},
	{"ntko", eKillComplication::Live},
	{"notargetko", eKillComplication::Live},
	{"notargetpacification", eKillComplication::Live},
	{"nopacification", eKillComplication::Live},
	{"nopacify", eKillComplication::Live},
	{"notargetknockout", eKillComplication::Live},
	{"noknockout", eKillComplication::Live},
	{"notargetpacify", eKillComplication::Live},
	{"donotko", eKillComplication::Live},
	{"donotpacify", eKillComplication::Live},
	{"nonpacify", eKillComplication::Live},
	{"nonpacification", eKillComplication::Live},
};
const std::unordered_map<std::string, eKillType> killTypeKeywords = {
	{"loud", eKillType::Loud},
	{"ld", eKillType::Loud},
	{"silenced", eKillType::Silenced},
	{"silence", eKillType::Silenced},
	{"sil", eKillType::Silenced},
	{"silent", eKillType::Silenced},
	{"melee", eKillType::Melee},
	{"mel", eKillType::Melee},
	{"thrown", eKillType::Thrown},
	{"throw", eKillType::Thrown},
	{"remote", eKillType::Remote},
	{"impact", eKillType::Impact},
	{"imp", eKillType::Impact},
	{"rem", eKillType::Remote},
	{"loudremote", eKillType::LoudRemote},
	{"ldremote", eKillType::LoudRemote},
	{"loudrem", eKillType::LoudRemote},
	{"ldrem", eKillType::LoudRemote},
};

const KeywordInitialiser KeywordInitialiser::inst;

KeywordInitialiser::KeywordInitialiser() {
	for (auto const& vec : targetKeywordVec) {
		for (auto i = 1; i < vec.size(); ++i)
			targetKeywords.emplace(vec[i], vec[0]);
	}
}
