//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Croupier.UI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection CustomMissionPool {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["CustomMissionPool"]));
            }
            set {
                this["CustomMissionPool"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int MissionPool {
            get {
                return ((int)(this["MissionPool"]));
            }
            set {
                this["MissionPool"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Ruleset {
            get {
                return ((string)(this["Ruleset"]));
            }
            set {
                this["Ruleset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Ruleset_Custom_GenericEliminations {
            get {
                return ((bool)(this["Ruleset_Custom_GenericEliminations"]));
            }
            set {
                this["Ruleset_Custom_GenericEliminations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Ruleset_Custom_LiveComplications {
            get {
                return ((bool)(this["Ruleset_Custom_LiveComplications"]));
            }
            set {
                this["Ruleset_Custom_LiveComplications"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Ruleset_Custom_LiveComplicationsExcludeStandard {
            get {
                return ((bool)(this["Ruleset_Custom_LiveComplicationsExcludeStandard"]));
            }
            set {
                this["Ruleset_Custom_LiveComplicationsExcludeStandard"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public int Ruleset_Custom_LiveComplicationChance {
            get {
                return ((int)(this["Ruleset_Custom_LiveComplicationChance"]));
            }
            set {
                this["Ruleset_Custom_LiveComplicationChance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Ruleset_Custom_MeleeKillTypes {
            get {
                return ((bool)(this["Ruleset_Custom_MeleeKillTypes"]));
            }
            set {
                this["Ruleset_Custom_MeleeKillTypes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Ruleset_Custom_ThrownKillTypes {
            get {
                return ((bool)(this["Ruleset_Custom_ThrownKillTypes"]));
            }
            set {
                this["Ruleset_Custom_ThrownKillTypes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Ruleset_Custom_BannedMedium {
            get {
                return ((bool)(this["Ruleset_Custom_BannedMedium"]));
            }
            set {
                this["Ruleset_Custom_BannedMedium"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Ruleset_Custom_BannedHard {
            get {
                return ((bool)(this["Ruleset_Custom_BannedHard"]));
            }
            set {
                this["Ruleset_Custom_BannedHard"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Ruleset_Custom_BannedExtreme {
            get {
                return ((bool)(this["Ruleset_Custom_BannedExtreme"]));
            }
            set {
                this["Ruleset_Custom_BannedExtreme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Ruleset_Custom_BannedImpossible {
            get {
                return ((bool)(this["Ruleset_Custom_BannedImpossible"]));
            }
            set {
                this["Ruleset_Custom_BannedImpossible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Ruleset_Custom_BannedBuggy {
            get {
                return ((bool)(this["Ruleset_Custom_BannedBuggy"]));
            }
            set {
                this["Ruleset_Custom_BannedBuggy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Width1Column {
            get {
                return ((double)(this["Width1Column"]));
            }
            set {
                this["Width1Column"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Width2Column {
            get {
                return ((double)(this["Width2Column"]));
            }
            set {
                this["Width2Column"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AlwaysOnTop {
            get {
                return ((bool)(this["AlwaysOnTop"]));
            }
            set {
                this["AlwaysOnTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RightToLeft {
            get {
                return ((bool)(this["RightToLeft"]));
            }
            set {
                this["RightToLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VerticalDisplay {
            get {
                return ((bool)(this["VerticalDisplay"]));
            }
            set {
                this["VerticalDisplay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StaticSize {
            get {
                return ((bool)(this["StaticSize"]));
            }
            set {
                this["StaticSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StaticSizeLHS {
            get {
                return ((bool)(this["StaticSizeLHS"]));
            }
            set {
                this["StaticSizeLHS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection SpinHistory {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SpinHistory"]));
            }
            set {
                this["SpinHistory"] = value;
            }
        }
    }
}
